[workspace]
members = [ "crates/benches", "crates/bvh", "crates/block", "crates/common", "crates/ecs", "crates/game", "crates/macros", "crates/nbt", "crates/protocol", "crates/server", "crates/world", "crates/hyperion_bvh"]
