[package]
name = "serverx-world"
version = "0.1.0"
edition = "2021"

[dependencies]
serverx-block = { path = "../block" }
serverx-common = { path = "../common" }
serverx-nbt = { path = "../nbt" }
serverx-macros = { path = "../macros" }
num-integer = "0.1.46"
